name: Gradle CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Gradle
        run: gradle shadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: GeniusLogger
          path: |
            build/libs/GeniusLogger-all.jar
            jre1.8.0_202
            Run.bat